// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA67c6gOwm6NGaocm3kLp12WOQ6oGgB65Q',
    appId: '1:694432095218:web:3882fee0003a332e4d696b',
    messagingSenderId: '694432095218',
    projectId: 'part-delivery-app',
    authDomain: 'part-delivery-app.firebaseapp.com',
    storageBucket: 'part-delivery-app.firebasestorage.app',
    measurementId: 'G-85W1JL2EBH',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCjAhk77zU_7fUiQ3rl94ZSU0nIVRNp6co',
    appId: '1:694432095218:android:bd332be60f8bce5d4d696b',
    messagingSenderId: '694432095218',
    projectId: 'part-delivery-app',
    storageBucket: 'part-delivery-app.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCHNZr85wfyPksfqcTbQLaXGTuPE75iESE',
    appId: '1:694432095218:ios:5c6d432b299451744d696b',
    messagingSenderId: '694432095218',
    projectId: 'part-delivery-app',
    storageBucket: 'part-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.fluttterProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCHNZr85wfyPksfqcTbQLaXGTuPE75iESE',
    appId: '1:694432095218:ios:5c6d432b299451744d696b',
    messagingSenderId: '694432095218',
    projectId: 'part-delivery-app',
    storageBucket: 'part-delivery-app.firebasestorage.app',
    iosBundleId: 'com.example.fluttterProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA67c6gOwm6NGaocm3kLp12WOQ6oGgB65Q',
    appId: '1:694432095218:web:b97600b38fd8b0694d696b',
    messagingSenderId: '694432095218',
    projectId: 'part-delivery-app',
    authDomain: 'part-delivery-app.firebaseapp.com',
    storageBucket: 'part-delivery-app.firebasestorage.app',
    measurementId: 'G-3VQMKQ07R6',
  );
}
